The automatically calculated lowfreq cutoff is: 2

Total kmer species:     1249835
Total kmer individuals: 30999528
Total kmer species (lowfreq excluded): 1249760
Total kmer individuals(lowfreq excluded): 30999433

Number of lowfreq Kmer species caused by sequencing errors: 75
	Ratio in all kmer species: 6.0007921045578e-05
Number of lowfreq Kmer individuals caused by sequencing errors: 95
	Ratio in all kmer individuals: 3.06456278947215e-06

Integer c by p(x) and f(x): 19	20

The estimated float-point expected coverage depth:
	c by P(x): 20.010492928444 	 using 6 points
	c by F(x): 20.093082490328 	 using 6 points
	c by P(x) and F(x): 20.051787709386

The roughly estimated genome size (nk filtered but not adjusted):
	G by P(x): 1549158
	G by F(x): 1542791
	G by P(x) and F(x): 1545968
